name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "FLASK_APP=app.py" >> $GITHUB_ENV
          echo "FLASK_ENV=development" >> $GITHUB_ENV
      - name: Install Dependencies
        run: |
          pip install flask 
          pip install pytest

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          pip install pytest
      - name: Run Tests
        run: pytest unit_tests.py

  run-api:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start API
        run: python app.py &

  deploy-to-dev:
    needs: run-api
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev Environment
        run: echo "http://localhost:5000"
